version: 1.0.{build}
image: Ubuntu2004
clone_depth: 1
init:
  - sh: sudo apt update
  - sh: sudo apt-get --ignore-missing -y install ^python3$ ^python3.6$ ^python3.7$ ^python3.8$ ^python3.9$ ^python3.10$
environment:
  matrix:
    - TOXENV: py36
    - TOXENV: py37
    - TOXENV: py38
    - TOXENV: py39
    - TOXENV: py310
build: false
install:
  - python3 -m pip install --upgrade pip
  - python3 -m pip install tox
test_script:
  - python3 -m tox
