version: 1.0.{build}
image: Ubuntu
clone_depth: 1
environment:
  matrix:
    - TOXENV: py36
    - TOXENV: py37
    - TOXENV: py38
    - TOXENV: py39
    - TOXENV: py310
build: false
install:
  - py -m pip install --upgrade pip
  - py -m pip install tox
test_script:
  - py -m tox
