version: 1.0.{build}
image: Ubuntu2004
clone_depth: 1
init:
  - sh: echo $PY_VER
  - sh: source $HOME/venv$PY_VER
  - sh: python --version
environment:
  matrix:
    - TOXENV: py36
      PY_VER: 3.6
    - TOXENV: py37
      PY_VER: 3.7
    - TOXENV: py38
      PY_VER: 3.8
    - TOXENV: py39
      PY_VER: 3.9
    - TOXENV: py310
      PY_VER: 3.10
build: false
install:
  - python -m pip install --upgrade pip
  - python -m pip install tox
test_script:
  - python -m tox
