version: 1.0.{build}
image: Ubuntu
clone_depth: 1
init:
  - sh: python3 --version
environment:
  matrix:
    - TOXENV: py36
    - TOXENV: py37
    - TOXENV: py38
    - TOXENV: py39
    - TOXENV: py310
build: false
install:
  - python3 -m pip install --upgrade pip
  - python3 -m pip install tox
test_script:
  - python3 -m tox
